<div class="indicator2">
    <h4 class='title' data-bind="i18n:'Payment could not be completed!'"></h4>
    <h4 class='title' data-bind="i18n:'Processing'"></h4>
    <span class="loader"></span>
</div>
<style>
    .indicator2{
        width: 100%;
        background: #fff;
        line-height: 100vh;
        text-align: center;
        position: absolute;
        opacity: .7;
        z-index: 9999;
    }

    .indicator2 .title {
        margin: 10px;
        font-size: 18px;
        font-family: inherit;
        color: inherit;
    }

    .indicator2 .loader {
        position: absolute;
        left: 50%;
        top: 300%;
        margin-left: -60px;
        border: 16px solid #f3f3f3;
        border-top: 16px solid #3498db;
        border-radius: 50%;
        width: 120px;
        height: 120px;
        animation: spin 1.5s linear infinite;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>
<script>
    setTimeout(function(){parent.window.closePaymentVantiv()},4000);
</script>